/** Exports compiled ABIs from Foundry's `out/` into a typed TS module: pnpm --filter @mohar/core abi */
import { readFileSync, writeFileSync } from "node:fs";

const read = (name: string) =>
  JSON.parse(readFileSync(new URL(`../../contracts/out/${name}.sol/${name}.json`, import.meta.url), "utf8")).abi;

const body = `// GENERATED by scripts/export-abi.ts from packages/contracts/out. Do not edit by hand.
export const issuerRegistryAbi = ${JSON.stringify(read("IssuerRegistry"), null, 2)} as const;

export const certificateRegistryAbi = ${JSON.stringify(read("CertificateRegistry"), null, 2)} as const;
`;
writeFileSync(new URL("../src/abi.generated.ts", import.meta.url), body);
console.log("abi.generated.ts written");
